default_platform(:ios)

platform :ios do
  desc "Build and distribute iOS app to Firebase"
  lane :distribute do
    build_app(
      scheme: "Runner",
      export_method: "ad-hoc" # "ad-hoc" # หรือ "development" ถ้าทดสอบเฉพาะนักพัฒนา
    )

    firebase_app_distribution(
      app: "1:38464663708:android:66ddbaff64d15a7c123d59", # ใส่ App ID ของ Firebase (ดูใน Firebase Console)
      firebase_cli_token: ENV["FIREBASE_TOKEN"], # ใช้ Token ถ้าไม่ได้ Login
      ipa_path: "./build/ios/ipa/Runner.ipa",
      #testers: "tester@email.com", # ใส่อีเมลของผู้ทดสอบ
      tester_groups: "Intern,Nightbears,Newdice", # ชื่อกลุ่มใน Firebase
      release_notes: "New update for testing"
    )
  end
end
